language: node_js
cache:
  directories:
  - node_modules
matrix:
  include:
  - os: linux
node_js:
  - "12"
script: "npm run-script validate:index && npm run-script validate:aliases && npm run-script validate:devices"
