name: Continuous Integration

on:
  push:
    branches: [master, bye-bye-node]
  pull_request:
    branches: [master]

jobs:
  prerequisites:
    name: Prerequisites
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v4
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: Containerfile.ci
          tags: localci:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: localci:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            for device in /work/v2/devices/*.yml; do
              jv /work/v2/schema/_.schema.yml "${device}"
              /app/extra_validations.py "${device}"
            done
